title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
github:repository_url: https://github.com/710241969/710241969.github.io